<?php

namespace Database\Seeders;

use App\Models\GeneralSetup;
use App\Models\FormInput;
use Illuminate\Database\Seeder;
use Faker\Generator as Faker;

class GeneralSetupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(Faker $faker)
    {
        $generalSetUp = new GeneralSetup();
        $generalSetUp->company_id = 1;
        $generalSetUp->general_table_id = rand(1, 10);
        $generalSetUp->currencie_id = rand(1, 10);
        $generalSetUp->currency_position = "Left";
        $generalSetUp->language_id = rand(1, 10);
        $generalSetUp->input_display_type = 'Horizontal';
        $generalSetUp->stock_account_method = 'FIFO';
        $generalSetUp->timezone ="Africa/Casablanca";// $faker->timezone();
        $generalSetUp->dateformat = "YYYY-MM-DD";
        $generalSetUp->is_store = 1;
        $generalSetUp->is_branch = "No";
        $generalSetUp->default_datatable_list_number = 10;
        $generalSetUp->transaction_edit_days = 10;
        $generalSetUp->decimal_separate = ",";
        $generalSetUp->thousand_separate = ",";
        $generalSetUp->discount_type = "%";
        $generalSetUp->voucher_length = 8;
        $generalSetUp->product_prefix = "PRID";
        $generalSetUp->account_prefix = "ACID";
        $generalSetUp->service_prefix = "SEID";
        $generalSetUp->supplier_prefix = "SUID";
        $generalSetUp->customer_prefix = "CUID";
        $generalSetUp->purchases_order_prefix = "POID";
        $generalSetUp->purchases_prefix = "PUID";
        $generalSetUp->purchases_requisition_prefix = "PRID";
        $generalSetUp->sales_prefix = "SAID";
        $generalSetUp->delivery_challans_prefix = "DCID";
        $generalSetUp->purchases_payment_prefix = "PAID";
        $generalSetUp->sales_payment_prefix = "SAIP";
        $generalSetUp->service_invoice_prefix = "SIID";
        $generalSetUp->service_quatation_prefix = "SQID";
        $generalSetUp->sales_quatation_prefix = "SQID";
        $generalSetUp->payment_voucher_prefix = 'PVID';
        $generalSetUp->receive_voucher_prefix = 'RVID';
        $generalSetUp->journal_voucher_prefix = 'JVID';
        $generalSetUp->customer_opening_prefix = 'COID';
        $generalSetUp->supplier_opening_prefix = 'SOID';
        $generalSetUp->inventory_opening_prefix = 'IOID';
        $generalSetUp->hotel_booking_prefix = 'HBID';
        $generalSetUp->inventory_adjust_approval = 'Auto Approval';
        $generalSetUp->inventory_adjust_prefix = 'IAID';
        $generalSetUp->purchases_mrr_prefix = 'PMID';
        $generalSetUp->purchases_pending_cheque_prefix = 'PEID';
        $generalSetUp->sales_pending_cheque_prefix = 'SEID';
        $generalSetUp->purchases_mrr = 'Yes';
        $generalSetUp->delivery_challan = 'Yes';
        $generalSetUp->mrr_approval = 'Auto Approval';
        $generalSetUp->challan_approval = 'Auto Approval';
        $generalSetUp->price_calculate_type = 'Round';
        $generalSetUp->transfer_prefix = 'TRID';
        $generalSetUp->sales_approval = 'Auto Approval';
        $generalSetUp->account_approval = 'Auto Approval';
        $generalSetUp->inventory_approval = 'Auto Approval';
        $generalSetUp->purchases_return_approval = 'Auto Approval';
        $generalSetUp->sales_return_approval = 'Auto Approval';
        $generalSetUp->head_prefix = 'ACID';
        $generalSetUp->sales_loan_return_prefix = 'SLRID';
        $generalSetUp->pos_prefix = 'POSID';
        $generalSetUp->contra_voucher_prefix = 'CVID';
        $generalSetUp->purchases_sms = 'No';
        $generalSetUp->purchases_email = 'No';
        $generalSetUp->purchases_download = 'No';
        $generalSetUp->sales_sms = 'No';
        $generalSetUp->sales_email = 'No';
        $generalSetUp->sales_download = 'No';
        $generalSetUp->account_sms = 'No';
        $generalSetUp->account_email = 'No';
        $generalSetUp->account_download = 'No';
        $generalSetUp->service_sms = 'No';
        $generalSetUp->service_email = 'No';
        $generalSetUp->service_download = 'No';

        $generalSetUp->pos_prefix = 'POS';
        $generalSetUp->pos_approval = 'Auto Approval';

        
        $generalSetUp->updated_by = 1;
        $generalSetUp->created_by = 1;
        $generalSetUp->deleted_by = 1;
        $generalSetUp->save();
        $formStructure = array(
            'name' => 'general_setups',
            'input_field' => array(
                array(
                    'name' => 'is_branch',
                    'type' => 'select',
                    'class' => 'form-control select2 is_branch',
                    'id' => null,
                    'label' => 'Branch Type',
                    'placeholder' => 'Branch Type',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'customMethod' => 'getSetupData(11)',
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'is_store',
                    'type' => 'checkbox',
                    'class' => 'form-control is_store',
                    'id' => null,
                    'label' => 'Is Store Enable ?',
                    'placeholder' => 'Is Store Enable',
                    'value' => null,
                    'required' => null,
                    'hideDiv' => 'hide',
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'company_id',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Company Category',
                    'placeholder' => 'Select Company name',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => 'company_categories',
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'default_datatable_list_number',
                    'type' => 'number',
                    'class' => 'form-control',
                    'id' => null,
                    'label' => 'Voucher List [Skip Type 0]',
                    'placeholder' => 'Voucher List [Skip Type 0]',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'transaction_edit_days',
                    'type' => 'number',
                    'class' => 'form-control',
                    'id' => null,
                    'label' => 'Transaction Edit Days [Skip Type 0]',
                    'placeholder' => 'Transaction Edit Days [Skip Type 0]',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'input_display_type',
                    'type' => 'select',
                    'class' => 'form-control',
                    'id' => null,
                    'label' => 'Input Display Type',
                    'placeholder' => 'Input Display Type',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'customMethod' => 'getSetupData(8)',
                    'validation' => null,
                    'category' => 'General',
                ),
                array(
                    'name' => 'stock_account_method',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Stock Store Type',
                    'placeholder' => 'Stock Store Type',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'customMethod' => 'getSetupData(9)',
                    'validation' => null,
                    'category' => 'General',
                ),

                array(
                    'name' => 'currencie_id',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Select Currency',
                    'placeholder' => 'Currency Currency',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'foreignTable' => 'currencies',
                    'category' => 'General',
                ),
                array(
                    'name' => 'currency_position',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Currency Position',
                    'placeholder' => 'Currency Position',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'validation' => 'nullable',
                    'customMethod' => 'getSetupData(6)',
                    'category' => 'General',
                ),
                array(
                    'name' => 'language_id',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Language',
                    'placeholder' => 'Please type language',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => false,
                    'unique' => false,
                    'validation' => 'nullable',
                    'foreignTable' => 'languages',
                    'category' => 'General',
                ),
                array(
                    'name' => 'timezone',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Timezone',
                    'placeholder' => 'Please select timezone',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(1)',
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'dateformat',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Dateformat',
                    'placeholder' => 'Please select dateformat',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(2)',
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'decimal_separate',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Decimal Separate',
                    'placeholder' => 'Please select decimal Separate',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(3)',
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'price_calculate_type',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Price Calculate Type',
                    'placeholder' => 'Price Calculate Type',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(15)',
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'thousand_separate',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Thousand separate',
                    'placeholder' => 'Please select thousand separate',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(3)',
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'discount_type',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Discount Type',
                    'placeholder' => 'Please select Discount Type',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(5)',
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'voucher_length',
                    'type' => 'text',
                    'class' => 'form-control',
                    'id' => null,
                    'label' => 'Voucher Length',
                    'placeholder' => 'Voucher Length',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'General',
                ),
                array(
                    'name' => 'product_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Product Prefix',
                    'placeholder' => 'Product Prefix',
                    'value' => "PRID",
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Purchases',

                ),

                array(
                    'name' => 'inventory_approval',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Purchases Approval',
                    'placeholder' => 'Select Approval Type',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(4)',
                    'validation' => 'nullable',
                    'category' => 'Purchases',
                ),

                array(
                    'name' => 'purchases_return_approval',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Purchases Return Approval',
                    'placeholder' => 'Select Approval Type',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(4)',
                    'validation' => 'nullable',
                    'category' => 'Purchases',
                ),

                array(
                    'name' => 'purchases_mrr',
                    'type' => 'select',
                    'class' => 'form-control select2 purchases_mrr',
                    'id' => null,
                    'label' => 'Purchases MRR',
                    'placeholder' => 'Purchases MRR',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Purchases',
                ),
                array(
                    'name' => 'purchases_email',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Purchases Email',
                    'placeholder' => 'Purchases Email',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Purchases',
                ),
                array(
                    'name' => 'purchases_download',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Purchases Download',
                    'placeholder' => 'Purchases Download',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Purchases',
                ),
                array(
                    'name' => 'purchases_sms',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Purchases SMS',
                    'placeholder' => 'Purchases SMS',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Purchases',
                ),
                array(
                    'name' => 'sales_sms',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Sales SMS',
                    'placeholder' => 'Sales SMS',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Sales',
                ),
                array(
                    'name' => 'sales_email',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Sales Email',
                    'placeholder' => 'Sales Email',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Sales',
                ),
                array(
                    'name' => 'sales_download',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Sales Download',
                    'placeholder' => 'Sales Download',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Sales',
                ),
                array(
                    'name' => 'account_sms',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Account SMS',
                    'placeholder' => 'Account SMS',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Account',
                ),
                array(
                    'name' => 'account_email',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Account Email',
                    'placeholder' => 'Account Email',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Account',
                ),
                array(
                    'name' => 'account_download',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Account Download',
                    'placeholder' => 'Account Download',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Account',
                ),
                array(
                    'name' => 'service_sms',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Service SMS',
                    'placeholder' => 'Service SMS',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Service',
                ),
                array(
                    'name' => 'service_email',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Service Email',
                    'placeholder' => 'Service Email',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Service',
                ),
                array(
                    'name' => 'service_download',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Service Download',
                    'placeholder' => 'Service Download',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Service',
                ),


                array(
                    'name' => 'mrr_approval',
                    'type' => 'select',
                    'class' => 'form-control select2 mrr_approval',
                    'id' => null,
                    'label' => 'MRR Approbal',
                    'placeholder' => 'MRR Approbal',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'hideDiv' => 'hide',
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(4)',
                    'validation' => 'nullable',
                    'category' => 'Purchases',
                ),
               

                array(
                    'name' => 'supplier_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Supplier Prefix',
                    'placeholder' => 'Supplier Prefix',
                    'value' => 'SUID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Purchases',

                ),
                array(
                    'name' => 'customer_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Customer Prefix',
                    'placeholder' => 'Customer Prefix',
                    'value' => 'CUID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Sales',

                ),
                array(
                    'name' => 'purchases_order_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Purchases Order Prefix',
                    'placeholder' => 'Purchases Order Prefix',
                    'value' => 'POID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Purchases',
                ),
                array(
                    'name' => 'purchases_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Purchases Prefix',
                    'placeholder' => '',
                    'value' => 'PUID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Purchases',

                ),
                array(
                    'name' => 'purchases_pending_cheque_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Pending Cheque Prefix',
                    'placeholder' => '',
                    'value' => 'PEID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Purchases',

                ),
                array(
                    'name' => 'purchases_payment_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Purchases Payment Prefix',
                    'placeholder' => '',
                    'value' => 'PAID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Purchases',

                ),
            
                array(
                    'name' => 'sales_payment_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Sales Payment Prefix',
                    'placeholder' => '',
                    'value' => 'SAID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Sales',

                ),
                array(
                    'name' => 'purchases_requisition_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Purchases Requisition Prefix',
                    'placeholder' => 'Purchases Requisition Prefix',
                    'value' => 'PRID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Purchases',

                ),
                array(
                    'name' => 'delivery_challan',
                    'type' => 'select',
                    'class' => 'form-control select2 delivery_challan',
                    'id' => null,
                    'label' => 'Delivery Challan',
                    'placeholder' => 'Delivery Challan',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(14)',
                    'validation' => 'nullable',
                    'category' => 'Sales',
                ),

                array(
                    'name' => 'sales_return_approval',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Sales Return Approval',
                    'placeholder' => 'Select Approval Type',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(4)',
                    'validation' => 'nullable',
                    'category' => 'Sales',
                ),

                array(
                    'name' => 'challan_approval',
                    'type' => 'select',
                    'class' => 'form-control select2 challan_approval',
                    'id' => null,
                    'label' => 'Challan Approbal',
                    'placeholder' => 'Challan Approbal',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'hideDiv' => 'hide',
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(4)',
                    'validation' => 'nullable',
                    'category' => 'Sales',
                ),

             
                array(
                    'name' => 'sales_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Sales Prefix',
                    'placeholder' => 'Sales Prefix',
                    'value' => 'SAID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Sales',
                ),
                array(
                    'name' => 'delivery_challans_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Delivery Challan Prefix',
                    'placeholder' => 'Delivery Challan Prefix',
                    'value' => 'DCID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Sales',

                ),
                array(
                    'name' => 'sales_quatation_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Sales Quatation Prefix',
                    'placeholder' => 'Sales Quatation Prefix',
                    'value' => 'SQID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Sales',

                ),
                array(
                    'name' => 'sales_pending_cheque_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Pending Cheque Prefix',
                    'placeholder' => 'Pending Cheque  Prefix',
                    'value' => 'PEID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Sales',

                ),
                
                array(
                    'name' => 'payment_voucher_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Payment Voucher Prefix',
                    'placeholder' => 'Payment Voucher Prefix',
                    'value' => 'PAID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Account',

                ),
                array(
                    'name' => 'contra_voucher_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Contra Voucher Prefix',
                    'placeholder' => 'Contra Voucher Prefix',
                    'value' => 'CVID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Account',

                ),
                array(
                    'name' => 'receive_voucher_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Receive Voucher Prefix',
                    'placeholder' => 'Receive Voucher Prefix',
                    'value' => 'RUID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Account',

                ),
                array(
                    'name' => 'journal_voucher_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Journal Voucher Prefix',
                    'placeholder' => 'Journal Voucher Prefix',
                    'value' => 'JUID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Account',
                ),
                array(
                    'name' => 'head_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Account Head Prefix',
                    'placeholder' => 'Account Head Prefix',
                    'value' => 'ACID',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Account',
                ),

                array(
                    'name' => 'service_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Service Prefix',
                    'placeholder' => 'Service Prefix',
                    'value' => "SAID",
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Service',

                ),

                array(
                    'name' => 'service_invoice_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Service Invoice Prefix',
                    'placeholder' => 'Service Invoice Prefix',
                    'value' => "SIID",
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Service',

                ),
                array(
                    'name' => 'service_quatation_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Service Quatation Prefix',
                    'placeholder' => 'Service Quatation Prefix',
                    'value' => "SQID",
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Service',
                ),
                array(
                    'name' => 'service_invoice_approbal',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Service Invoice Approbal',
                    'placeholder' => 'Service Invoice Approbal',
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(4)',
                    'validation' => 'nullable',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Service',
                ),
                array(
                    'name' => 'sales_approval',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Sales Approval',
                    'placeholder' => 'Please select Sales Approval',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(4)',
                    'validation' => 'nullable',
                    'category' => 'Sales',
                ),
                array(
                    'name' => 'account_approval',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Account Approval',
                    'placeholder' => 'Please select Account Approval',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(4)',
                    'validation' => 'nullable',
                    'category' => 'Account',
                ),
                array(
                    'name' => 'inventory_opening_prefix',
                    'type' => 'text',
                    'class' => 'form-control',
                    'id' => null,
                    'label' => 'Inventory Opening Prefix',
                    'placeholder' => 'Inventory Opening Prefix',
                    'value' => 'IOID',
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'validation' => 'nullable',
                    'category' => 'Opening',
                ),
                array(
                    'name' => 'supplier_opening_prefix',
                    'type' => 'text',
                    'class' => 'form-control',
                    'id' => null,
                    'label' => 'Supplier Opening Prefix',
                    'placeholder' => 'Supplier Opening Prefix',
                    'value' => 'SOID',
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'validation' => 'nullable',
                    'category' => 'Opening',
                ),
                array(
                    'name' => 'customer_opening_prefix',
                    'type' => 'text',
                    'class' => 'form-control',
                    'id' => null,
                    'label' => 'Customer Opening Prefix',
                    'placeholder' => 'Customer Opening Prefix',
                    'value' => 'COID',
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'validation' => 'nullable',
                    'category' => 'Opening',
                ),

                array(
                    'name' => 'status',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Status',
                    'placeholder' => 'Select Status',
                    'value' => null,
                    'required' => null,
                    'unique' => false,
                    'tableshow' => true,
                    'inputShow' => true,
                    'customMethod' => null,
                    'foreignTable' => 'statuses',
                    'validation' => 'nullable',

                ),

                array(
                    'name' => 'pos_approval',
                    'type' => 'select',
                    'class' => 'form-control select2 pos_approval',
                    'id' => null,
                    'label' => 'Pos Approbal',
                    'placeholder' => 'Pos Approbal',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,  
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(4)',
                    'validation' => 'nullable',
                    'category' => 'Pos',
                ),
                array(
                    'name' => 'pos_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'POS Prefix',
                    'placeholder' => 'Pos Prefix',
                    'value' => 'POS',
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Pos',
                ),
                array(
                    'name' => 'inventory_adjust_prefix',
                    'type' => 'text',
                    'class' => 'form-control readonly',
                    'id' => null,
                    'label' => 'Inventory Adjustment Prefix',
                    'placeholder' => 'Inventory Adjustment Prefix',
                    'value' => "IAID",
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'validation' => 'nullable',
                    'category' => 'Inventory_Adjustment',

                ),
                
                array(
                    'name' => 'inventory_adjust_approval',
                    'type' => 'select',
                    'class' => 'form-control select2',
                    'id' => null,
                    'label' => 'Inventory Adjustment Approval',
                    'placeholder' => 'Please Inventory Adjustment Approval',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    'customMethod' => 'getSetupData(4)',
                    'validation' => 'nullable',
                    'category' => 'Inventory_Adjustment',
                ),
                
            )
        );
        $formInfo = new FormInput();
        $formInfo->navigation_id = null;
        $formInfo->table = $formStructure['name'];
        $formInfo->input = json_encode($formStructure['input_field']);
        $formInfo->save();
    }
}