<?php

namespace Database\Seeders;

use App\Models\FormInput;
use Illuminate\Database\Seeder;

class ReportModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $formStructure =  array(
            'name' => 'report_models',
            'input_field' => array(
                array(
                    'name' => 'date_range',
                    'type' => 'rdateRange',
                    'class' => 'form-control',
                    'id' => null,
                    'label' => 'Date Range',
                    'placeholder' => 'Date Range',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),
                array(
                    'name' => 'date',
                    'type' => 'rdate',
                    'class' => 'form-control',
                    'id' => null,
                    'label' => 'Date',
                    'placeholder' => 'Date',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),
                array(
                    'name' => 'branch_id',
                    'type' => 'rselect',
                    'class' => 'form-control  select2 branch_id',
                    'id' => null,
                    'allOption' => true,
                    'label' => 'Branch',
                    'placeholder' => 'Branch',
                    'foreignTable' => 'branches',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),
                array(
                    'name' => 'store_id',
                    'type' => 'rselect',
                    'class' => 'form-control  select2 store_id',
                    'id' => null,
                    'allOption' => true,
                    'label' => 'Store',
                    'placeholder' => 'Store',
                    'foreignTable' => 'stores',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),
                array(
                    'name' => 'supplier_id',
                    'type' => 'rselect',
                    'class' => 'form-control select2 supplier_id',
                    'id' => null,
                    'allOption' => true,
                    'label' => 'Supplier ID',
                    'placeholder' => 'Supplier ID',
                    'value' => null,
                    'required' => null,
                    'foreignTable' => 'suppliers',
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),
                array(
                    'name' => 'customer_id',
                    'type' => 'rselect',
                    'class' => 'form-control  select2 customer_id',
                    'id' => null,
                    'allOption' => true,
                    'label' => 'Customer',
                    'placeholder' => 'Customer',
                    'foreignTable' => 'customers',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),

                array(
                    'name' => 'payment_type',
                    'type' => 'rselect',
                    'class' => 'form-control select2 payment_type sppayment_type',
                    'id' => null,
                    'label' => 'Payment Type',
                    'placeholder' => 'Please select Payment Type',
                    'value' => "Cash",
                    'required' => null,
                    'unique' => false,
                    'tableshow' => true,
                    'inputShow' => true,
                    'foreignTable' => null,
                    'customMethod' => 'getCashAndBankPaymentType()',
                    'validation' => 'required',
                ),


                array(
                    'name' => 'account_id',
                    'type' => 'roptionGroup',
                    'class' => 'form-control select2 account_id',
                    'id' => null,
                    'label' => 'Account Head',
                    'placeholder' => 'Select Account Head',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                ),
                array(
                    'name' => 'spp_account_id',
                    'type' => 'roptionGroup',
                    'class' => 'form-control select2 account_id',
                    'id' => null,
                    'label' => 'Account Head',
                    'placeholder' => 'Select Account Head',
                    'value' => null,
                    'required' => null,
                    'tableshow' => false,
                    'hideDiv' => 'hide',
                    'inputShow' => true,
                    'unique' => false,
                    'foreignTable' => null,
                    
                ),
                array(
                    'name' => 'bank_id',
                    'type' => 'rselect',
                    'class' => 'form-control  select2 bank_id spbank_id',
                    'id' => null,
                    'label' => 'Bank Name',
                    'placeholder' => 'Bank Name',
                    'foreignTable' => 'banks',
                    'value' => null,
                    'hideDiv' => 'hide',
                    'allOption' => true,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),
                array(
                    'name' => 'check_no',
                    'type' => 'rtext',
                    'class' => 'form-control check_no',
                    'id' => null,
                    'hideDiv' => 'hide',
                    'label' => 'Chcek No',
                    'placeholder' => 'Chcek No',
                    'value' => null,
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),

                array(
                    'name' => 'check_date',
                    'type' => 'check_date',
                    'class' => 'form-control check_date',
                    'id' => null,
                    'label' => 'Check Date',
                    'placeholder' => 'Check Date',
                    'value' => null,
                    'hideDiv' => 'hide',
                    'required' => null,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),
              
               
                array(
                    'name' => 'category_id',
                    'type' => 'rselect',
                    'class' => 'form-control select2 category_id',
                    'id' => null,
                    'label' => 'Category',
                    'placeholder' => 'Category',
                    'value' => null,
                    'required' => null,
                    'allOption' => true,
                    'foreignTable' => 'categories',
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),
               
                array(
                    'name' => 'product_id',
                    'type' => 'rselect',
                    'class' => 'form-control select2 product_id',
                    'id' => null,
                    'label' => 'Product',
                    'placeholder' => 'Product',
                    'value' => null,
                    'required' => null,
                    'allOption' => true,
                    'foreignTable' => 'products',
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),
                array(
                    'name' => 'batch_id',
                    'type' => 'rselect',
                    'class' => 'form-control select2 batch_id',
                    'id' => null,
                    'label' => 'Batch No',
                    'placeholder' => 'Batch No',
                    'value' => null,
                    'required' => null,
                    'allOption' => true,
                    'foreignTable' => 'batch_numbers',
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),

                
                array(
                    'name' => 'brand_id',
                    'type' => 'rselect',
                    'class' => 'form-control select2 brand_id',
                    'id' => null,
                    'label' => 'Brand',
                    'placeholder' => 'Brand',
                    'value' => null,
                    'required' => null,
                    'allOption' => true,
                    'foreignTable' => 'brands',
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                ),

              
                array(
                    'name' => 'purhcases_report_type',
                    'type' => 'rselect',
                    'class' => 'form-control select2 report_type_id',
                    'id' => null,
                    'label' => 'Report Type',
                    'placeholder' => 'Report Type',
                    'value' => null,
                    'required' => null,
                    'allOption' => false,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'customMethod' => 'getSetupData(16)',
                ),

                array(
                    'name' => 'sale_report_type',
                    'type' => 'rselect',
                    'class' => 'form-control select2 report_type_id',
                    'id' => null,
                    'label' => 'Report Type',
                    'placeholder' => 'Report Type',
                    'value' => null,
                    'required' => null,
                    'allOption' => false,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'customMethod' => 'getSetupData(17)',
                ),

                array(
                    'name' => 'stock_report_type',
                    'type' => 'rselect',
                    'class' => 'form-control select2 stock_report_type',
                    'id' => null,
                    'label' => 'Report Type',
                    'placeholder' => 'Report Type',
                    'value' => null,
                    'required' => null,
                    'allOption' => false,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'customMethod' => 'getSetupData(18)',
                ),
                array(
                    'name' => 'sales_report_type',
                    'type' => 'rselect',
                    'class' => 'form-control select2 sales_report_type',
                    'id' => null,
                    'label' => 'Report Type',
                    'placeholder' => 'Report Type',
                    'value' => null,
                    'required' => null,
                    'allOption' => false,
                    'tableshow' => true,
                    'inputShow' => true,
                    'unique' => false,
                    'customMethod' => 'getSetupData(20)',
                ),
                
               
            )
        );

        $formInfo = new FormInput();
        $formInfo->navigation_id = null;
        $formInfo->table = $formStructure['name'];
        $formInfo->input = json_encode($formStructure['input_field']);
        $formInfo->save();
    }
}
